[package]
name = "eulermat"
version = "0.1.0"
authors = ["Aryan Regmi <**>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18.0"

[dev-dependencies]
speculate = "0.1.2"
